version: '3.3'
services:

  wagi-server:
    image: registry.quant1.com.br/arthur/wagi-tests
    build:
      context: .
    container_name: wagi-server
    ports:
      - "${LOCAL_WAGI_BIND_PORT}:${LOCAL_WAGI_BIND_PORT}"
    environment:
      - LOCAL_WAGI_BIND_IP=${LOCAL_WAGI_BIND_IP}
      - LOCAL_WAGI_BIND_PORT=${LOCAL_WAGI_BIND_PORT}