version: '3.3'
services:

  wagi-server:
    image: wagi-test
    build:
      context: .
    container_name: wagi-server
    tty: true
    stdin_open: true
    ports:
      - "${LOCAL_WAGI_BIND_PORT}:${LOCAL_WAGI_BIND_PORT}"
    environment:
      - LOCAL_WAGI_BIND_IP=${LOCAL_WAGI_BIND_IP}
      - LOCAL_WAGI_BIND_PORT=${LOCAL_WAGI_BIND_PORT}